random_state: 4242
test_size: 0.3
shuffle: True
stratify: False
device: 'cpu'
batch_size: 30
num_epochs: 40
weights:
  - 1
  - 1
  - 1
early_stopping_patience: 10
select_features: False

optimizer:
  name: 'Adam'
  params:
    lr: 0.001
    weight_decay: 0.0001