paths:
  project: ${hydra:runtime.cwd}
  raw_data: ${.project}\data\raw
  models: ${.project}\models
  shares_dict: ${.project}\config\shares.yaml
  mean_volume_log: ${.project}\data\mean_volumes.json
  alerts: ${.project}\data\alerts.json
  trend_data: ${.project}\data\trend.csv
  selected_features: ${.project}\data\selected_features.json
  processed_data: ${.project}\data\processed

tokens:
  TOKEN:
  TOKEN_SANDBOX: 
  TELEGRAM_TOKEN: 'Provide your Telegram API token'

data:
  raw_data_filename: market_log
  processed_data_filename: dataset
  processed_data_labels_filename: labels
  raw_data_trades_columns:
    - time
    - buyers_count
    - buyers_quantity
    - sellers_count
    - sellers_quantity
  raw_data_orderbook_columns:
    - price
    - bids
    - asks
    - weighted_bid
    - weighted_ask
    - bid_to_ask_ratio
  trend_data_columns:
    - time
    - buy_count
    - buy_quantity
    - sell_count
    - sell_quantity
  data_labeling:
    time_column_name: time # modify this too if you modified any of the columns above
    price_column_name: price_last
    percent_change_threshold: 0.2
    min_time_interval: 90
    max_time_interval: 300
    label_meaning:
      hold: 0
      buy: 1
      sell: 2

  mean_volume:
    update_interval_days: 2
    candle_interval: 15_MIN
    mean_interval: 7
    api_wait_time: 1.1
    gather_function:
      _target_: src.data.mean_volume_gather.get_mean_volumes
  data_gather:
    buffer_write_delay: 500
    orderbook_depth: 10
    single_data_write_delay: 37
    request_delay: 5
    orderbook_processes:
      - min
      - max
      - std
features:
  - buy_sell_quantity_ratio
  - slope
trend_scan:
    time_delay: 60
volume_scan:
    session_time: 1_MIN # 1_MIN, 2_MIN, 3_MIN, 5_MIN, 10_MIN, 15_MIN available.
    time_delay: 60
    price_change_threshold: 0.2
    bigger_by_factor: 1

random_state: 1255141
test_size: 0.3

